# Generated by Django 4.1.6 on 2023-02-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patient_age_remove_patient_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
