# Generated by Django 4.1.6 on 2023-02-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecin', '0003_rename_specialite_medecin_specialisation'),
        ('patient', '0002_remove_patient_age_remove_patient_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_de_rdv', models.DateTimeField()),
                ('motif', models.TextField(max_length=255)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_reserved', to='medecin.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrient_reserved', to='patient.patient')),
            ],
        ),
    ]
