# Generated by Django 4.1.6 on 2023-02-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=10)),
                ('telephone', models.CharField(max_length=15)),
                ('specialite', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
