# Generated by Django 4.1.6 on 2023-02-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Medecin',
        ),
    ]
