# Generated by Django 4.1.6 on 2023-02-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0002_rename_patient_medecin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medecin',
            old_name='specialite',
            new_name='specialisation',
        ),
    ]
