# Generated by Django 4.1.6 on 2023-02-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0003_rename_specialite_medecin_specialisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
